import { Inter } from "next/font/google";
import "./assets/css/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Demo Next App",
  description: "Generated by rohits",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
